#!/usr/bin/env bash

set -e

help_text="
build_rpm_from_env_args [COMMAND]

    When run, this script will run 'rpm-setuptree' followed by 'rpmbuild'
    with all given environmental variables. See below for details and print
    out of current variables detected. 

COMMANDS:
    run   - Do the build (details above)
    help  - Print this help menu

ENV VARIABLES:
    SPEC_FILE_NAMES  - File names of '.spec' file in ~/rpmbuild/SPECS/ used (REQUIRED, comma delimited)
    PACKAGE_NAME     - Provided to 'rpmbuild' as variable: package_name
    PACKAGE_VERSION  - Provided to 'rpmbuild' as variable: package_version
    PACKAGE_LICENSE  - Provided to 'rpmbuild' as variable: package_license
    PACKAGE_SOURCE   - Provided to 'rpmbuild' as variable: package_source

DETECTED VARIABLE VALUES:
    SPEC_FILE_NAMES   - $SPEC_FILE_NAMES
    PACKAGE_NAME     - $PACKAGE_NAME
    PACKAGE_VERSION  - $PACKAGE_VERSION
    PACKAGE_LICENSE  - $PACKAGE_LICENSE
    PACKAGE_SOURCE   - $PACKAGE_SOURCE
"

function detect_env_var() {
    var_name="$1"
    var_value="${!var_name}"
    required="$2"

    if [[ "$required" = "true" ]] && [[ "$var_value" = "" ]]; then
        echo "Required variable '$var_name' not detected! Exiting."
        exit 1
    elif [[ "$var_value" = "" ]]; then
        echo "No value detected for variable '$var_name'"
    else
        echo "Value detected for variable '$var_name' = $var_value"   
    fi
}

function do_run() {
    detect_env_var "SPEC_FILE_NAMES" true
    detect_env_var "PACKAGE_NAME"
    detect_env_var "PACKAGE_VERSION"
    detect_env_var "PACKAGE_LICENSE"
    detect_env_var "PACKAGE_SOURCE"

    echo -e "\Running rpmdev-setuptree:"
    sudo rpmdev-setuptree

    # Split SPEC_FILE_NAMES by ',' for loop
    for SPEC_FILE_NAME in ${SPEC_FILE_NAMES//,/ }; do
        echo -e "\nBuilding rpm file for $SPEC_FILE_NAME:"
        rpmbuild -ba \
            --define "package_version $PACKAGE_VERSION" \
            --define "package_name $PACKAGE_NAME" \
            --define "package_license $PACKAGE_LICENSE" \
            --define "package_source $PACKAGE_SOURCE" \
            ~/rpmbuild/SPECS/"$SPEC_FILE_NAME"

        echo -e "\n\nBuild code: $?\n"
    done
}

function main() {
    case "$1" in
        "run")
            do_run
            exit 0
            ;;
        ""|"help"|"--help"|"-h")
            echo "$help_text"
            exit 0
            ;;
        *)
            echo "Command not recognized: $1"
            exit 1
            ;;
    esac
}

main $@
