#!/usr/bin/env bash

set -e

help_text="
setup_rpm_user.sh

    Takes two environmental variables (_USER_ID and _GROUP_ID) and creates
    a new user with which is added so the sudo'er list through membership
    in 'builder' group.

COMMANDS:
    run   - Do the build (details above)
    help  - Print this help menu

ENV VARIABLES:
    _USER_ID   - Name of new user to run script for (REQUIRED)
    _GROUP_ID  - Name of new group to run script for (REQUIRED)

DETECTED VARIABLE VALUES:
    _USER_ID   - $_USER_ID
    _GROUP_ID  - $_GROUP_ID
"

function detect_env_var() {
    var_name="$1"
    var_value="${!var_name}"
    required="$2"

    if [[ "$required" = "true" ]] && [[ "$var_value" = "" ]]; then
        echo "Required variable '$var_name' not detected! Exiting."
        exit 1
    elif [[ "$var_value" = "" ]]; then
        echo "No value detected for variable '$var_name'"
    else
        echo "Value detected for variable '$var_name' = $var_value"   
    fi
}

function do_run() {
    detect_env_var "_USER_ID" true
    detect_env_var "_GROUP_ID" true

    echo "Adding builder user/group ($_USER_ID:$_GROUP_ID)"
    groupadd -g "$_GROUP_ID" builder
    useradd -u "$_USER_ID" -g builder builder
    echo "builder        ALL=(ALL)       NOPASSWD: ALL" >> /etc/sudoers
    echo "Id for builder:"
    id builder
}

function main() {
    case "$1" in
        "run")
            do_run
            exit 0
            ;;
        ""|"help"|"--help"|"-h")
            echo "$help_text"
            exit 0
            ;;
        *)
            echo "Command not recognized: $1"
            exit 1
            ;;
    esac
}

main $@
